import type { PresentationType } from './types'

export const defaultPresentation: PresentationType = {
	title: 'Introducing Prezti',
	author: 'Prezti Team',
	date: new Date().toISOString().split('T')[0],
	version: '1.0',
	theme: {
		primaryColor: '#3b82f6',
		secondaryColor: '#000000',
		backgroundColor: '#ffffff',
		textColor: '#000000',
		headerFont: '"Inter", sans-serif',
		bodyFont: '"Inter", sans-serif',
	},
	slides: [
		{
			id: 'slide-1',
			layout: 'title-only',
			width: 960,
			height: 540,
			backgroundColor: '#ffffff',
			transition: { type: 'fade' },
			elements: [
				{
					id: 'element-1-1',
					type: 'heading',
					content: 'Beyond Templates.',
					x: 0,
					y: 120,
					width: 960,
					height: 100,
					style: { fontSize: '3.5rem', color: '#000000', textAlign: 'center', fontWeight: '300' },
				},
				{
					id: 'element-1-2',
					type: 'heading',
					content: 'AI presentations that understand your content.',
					x: 0,
					y: 220,
					width: 960,
					height: 80,
					style: { fontSize: '2.5rem', color: '#000000', textAlign: 'center', fontWeight: '300' },
				},
				{
					id: 'element-1-3',
					type: 'paragraph',
					content: 'Introducing Prezti - The open-source future of presentations',
					x: 0,
					y: 320,
					width: 960,
					height: 60,
					style: { fontSize: '1.5rem', color: '#000000', textAlign: 'center' },
				},
			],
		},
		{
			id: 'slide-2',
			layout: 'title-content',
			width: 960,
			height: 540,
			backgroundColor: '#ffffff',
			transition: { type: 'slide' },
			elements: [
				{
					id: 'element-2-1',
					type: 'heading',
					content: 'What is Prezti?',
					x: 0,
					y: 40,
					width: 960,
					height: 80,
					style: { fontSize: '2.5rem', color: '#111827', textAlign: 'left' },
				},
				{
					id: 'element-2-2',
					type: 'bullet-list',
					content: [
						'Open-source alternative to traditional presentation tools',
						'AI-powered content understanding and generation',
						'Self-hostable and fully customizable',
						'Turns ideas into professional presentations in seconds',
					],
					x: 0,
					y: 120,
					width: 960,
					height: 300,
					style: { fontSize: '1.5rem', color: '#374151', textAlign: 'left', lineHeight: '1.8' },
				},
			],
		},
		{
			id: 'slide-3',
			layout: 'title-content',
			width: 960,
			height: 540,
			backgroundColor: '#f9fafb',
			transition: { type: 'fade' },
			elements: [
				{
					id: 'element-3-1',
					type: 'heading',
					content: 'Key Features',
					x: 0,
					y: 40,
					width: 960,
					height: 80,
					style: { fontSize: '2.5rem', color: '#111827', textAlign: 'left' },
				},
				{
					id: 'element-3-2',
					type: 'bullet-list',
					content: [
						'🤖 AI-powered content generation',
						'🎨 Beautiful, modern templates',
						'🔧 Self-host and customize',
						'⚡ Lightning-fast creation',
						'🌐 Open-source transparency',
					],
					x: 0,
					y: 120,
					width: 960,
					height: 300,
					style: { fontSize: '1.5rem', color: '#374151', textAlign: 'left', lineHeight: '1.8' },
				},
			],
		},
		{
			id: 'slide-4',
			layout: 'title-content',
			width: 960,
			height: 540,
			backgroundColor: '#ffffff',
			transition: { type: 'fade' },
			elements: [
				{
					id: 'element-4-1',
					type: 'heading',
					content: 'Why Choose Prezti?',
					x: 0,
					y: 40,
					width: 960,
					height: 80,
					style: { fontSize: '2.5rem', color: '#111827', textAlign: 'left' },
				},
				{
					id: 'element-4-2',
					type: 'bullet-list',
					content: [
						'No vendor lock-in - own your data',
						"Customize to your organization's needs",
						'Community-driven development',
						'Privacy-first approach',
						'Cost-effective scaling',
					],
					x: 0,
					y: 120,
					width: 960,
					height: 300,
					style: { fontSize: '1.5rem', color: '#374151', textAlign: 'left', lineHeight: '1.8' },
				},
			],
		},
		{
			id: 'slide-5',
			layout: 'title-content',
			width: 960,
			height: 540,
			backgroundColor: '#111827',
			transition: { type: 'zoom' },
			elements: [
				{
					id: 'element-5-1',
					type: 'heading',
					content: 'Ready to Get Started?',
					x: 0,
					y: 120,
					width: 960,
					height: 80,
					style: { fontSize: '2.5rem', color: '#ffffff', textAlign: 'center' },
				},
				{
					id: 'element-5-2',
					type: 'paragraph',
					content: 'Join the waitlist and be among the first to experience the future of presentations.',
					x: 0,
					y: 220,
					width: 960,
					height: 60,
					style: { fontSize: '1.5rem', color: '#d1d5db', textAlign: 'center' },
				},
				{
					id: 'element-5-3',
					type: 'paragraph',
					content: 'Open-source. Self-hostable. AI-powered.',
					x: 0,
					y: 320,
					width: 960,
					height: 60,
					style: { fontSize: '1.2rem', color: '#9ca3af', textAlign: 'center', fontStyle: 'italic' },
				},
			],
		},
	],
}
