import type { SlideThemeType } from './types'

/**
 * Enhanced preset themes with background support - Complete Gallery Collection
 */
export const ENHANCED_PRESET_THEMES: SlideThemeType[] = [
	// === EXISTING THEMES ===
	{
		id: 'modern-minimal',
		name: 'Modern Minimal',
		category: 'professional',
		primaryColor: '#2563eb',
		secondaryColor: '#64748b',
		backgroundColor: '#ffffff',
		textColor: '#1e293b',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#ffffff',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1e293b',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: -0.5,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['minimal', 'professional', 'clean'],
			version: '1.0.0',
		},
	},
	{
		id: 'ocean-gradient',
		name: 'Ocean Gradient',
		category: 'creative',
		primaryColor: '#0891b2',
		secondaryColor: '#06b6d4',
		backgroundColor: '#f0f9ff',
		textColor: '#0c4a6e',
		headerFont: 'Nunito, system-ui',
		bodyFont: 'Roboto, system-ui',
		background: {
			type: 'gradient',
			gradient: {
				type: 'linear',
				angle: 135,
				stops: [
					{ color: '#0891b2', position: 0 },
					{ color: '#06b6d4', position: 50 },
					{ color: '#67e8f9', position: 100 },
				],
			},
		},
		illustrations: [],
		typography: {
			headingFont: 'Nunito, system-ui',
			bodyFont: 'Roboto, system-ui',
			headingColor: '#ffffff',
			bodyColor: '#f0f9ff',
			headingSizes: { h1: 52, h2: 44, h3: 36, h4: 28, h5: 22, h6: 18 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: true,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['gradient', 'ocean', 'blue', 'creative'],
			version: '1.0.0',
		},
	},
	// === NEW GALLERY THEMES ===
	{
		id: 'orbit',
		name: 'Orbit',
		category: 'professional',
		primaryColor: '#3b82f6',
		secondaryColor: '#1e40af',
		backgroundColor: '#1e1b4b',
		textColor: '#e0e7ff',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#1e1b4b',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#e0e7ff',
			bodyColor: '#c7d2fe',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 7.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['dark', 'professional', 'space', 'navy'],
			version: '1.0.0',
		},
	},
	{
		id: 'dune',
		name: 'Dune',
		category: 'basic',
		primaryColor: '#92400e',
		secondaryColor: '#d97706',
		backgroundColor: '#fef3c7',
		textColor: '#78350f',
		headerFont: 'Crimson Text, serif',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#fef3c7',
		},
		illustrations: [],
		typography: {
			headingFont: 'Crimson Text, serif',
			bodyFont: 'Inter, system-ui',
			headingColor: '#78350f',
			bodyColor: '#92400e',
			headingSizes: { h1: 46, h2: 38, h3: 30, h4: 22, h5: 18, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['warm', 'sand', 'earth', 'desert'],
			version: '1.0.0',
		},
	},
	{
		id: 'mocha',
		name: 'Mocha',
		category: 'professional',
		primaryColor: '#d4a574',
		secondaryColor: '#f59e0b',
		backgroundColor: '#451a03',
		textColor: '#fbbf24',
		headerFont: 'Playfair Display, serif',
		bodyFont: 'Source Sans Pro, system-ui',
		background: {
			type: 'color',
			color: '#451a03',
		},
		illustrations: [],
		typography: {
			headingFont: 'Playfair Display, serif',
			bodyFont: 'Source Sans Pro, system-ui',
			headingColor: '#fbbf24',
			bodyColor: '#d4a574',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['coffee', 'brown', 'warm', 'professional'],
			version: '1.0.0',
		},
	},
	{
		id: 'serene',
		name: 'Serene',
		category: 'basic',
		primaryColor: '#1e40af',
		secondaryColor: '#3b82f6',
		backgroundColor: '#ede9fe',
		textColor: '#1e1b4b',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#ede9fe',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1e1b4b',
			bodyColor: '#312e81',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['calm', 'purple', 'light', 'peaceful'],
			version: '1.0.0',
		},
	},
	{
		id: 'cornflower',
		name: 'Cornflower',
		category: 'creative',
		primaryColor: '#2563eb',
		secondaryColor: '#1d4ed8',
		backgroundColor: '#3b82f6',
		textColor: '#1e293b',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#3b82f6',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1e293b',
			bodyColor: '#334155',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['blue', 'vibrant', 'flower', 'bright'],
			version: '1.0.0',
		},
	},
	{
		id: 'vanilla',
		name: 'Vanilla',
		category: 'basic',
		primaryColor: '#92400e',
		secondaryColor: '#d97706',
		backgroundColor: '#fefce8',
		textColor: '#78350f',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#fefce8',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#78350f',
			bodyColor: '#92400e',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['cream', 'warm', 'soft', 'vanilla'],
			version: '1.0.0',
		},
	},
	{
		id: 'alien',
		name: 'Alien',
		category: 'creative',
		primaryColor: '#84cc16',
		secondaryColor: '#65a30d',
		backgroundColor: '#0f172a',
		textColor: '#ffffff',
		headerFont: 'Orbitron, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'gradient',
			gradient: {
				type: 'radial',
				center: { x: 80, y: 80 },
				stops: [
					{ color: '#0f172a', position: 0 },
					{ color: '#1e293b', position: 40 },
					{ color: '#166534', position: 80 },
					{ color: '#15803d', position: 100 },
				],
			},
		},
		illustrations: [],
		typography: {
			headingFont: 'Orbitron, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#ffffff',
			bodyColor: '#84cc16',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0.5,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: true,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['sci-fi', 'green', 'alien', 'futuristic'],
			version: '1.0.0',
		},
	},
	{
		id: 'breeze',
		name: 'Breeze',
		category: 'basic',
		primaryColor: '#1e40af',
		secondaryColor: '#2563eb',
		backgroundColor: '#dbeafe',
		textColor: '#1e293b',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#dbeafe',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1e293b',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['light', 'blue', 'airy', 'fresh'],
			version: '1.0.0',
		},
	},
	{
		id: 'aurora',
		name: 'Aurora',
		category: 'creative',
		primaryColor: '#a855f7',
		secondaryColor: '#ec4899',
		backgroundColor: '#1e1b4b',
		textColor: '#e0e7ff',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'gradient',
			gradient: {
				type: 'linear',
				angle: 135,
				stops: [
					{ color: '#1e1b4b', position: 0 },
					{ color: '#581c87', position: 30 },
					{ color: '#7c3aed', position: 60 },
					{ color: '#ec4899', position: 100 },
				],
			},
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#e0e7ff',
			bodyColor: '#c7d2fe',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: true,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['aurora', 'gradient', 'purple', 'mystical'],
			version: '1.0.0',
		},
	},
	{
		id: 'velvet-tides',
		name: 'Velvet Tides',
		category: 'creative',
		primaryColor: '#ec4899',
		secondaryColor: '#a855f7',
		backgroundColor: '#1e1b4b',
		textColor: '#f9fafb',
		headerFont: 'Playfair Display, serif',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'gradient',
			gradient: {
				type: 'radial',
				center: { x: 70, y: 30 },
				stops: [
					{ color: '#1e1b4b', position: 0 },
					{ color: '#581c87', position: 40 },
					{ color: '#be185d', position: 70 },
					{ color: '#ec4899', position: 100 },
				],
			},
		},
		illustrations: [],
		typography: {
			headingFont: 'Playfair Display, serif',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f9fafb',
			bodyColor: '#fce7f3',
			headingSizes: { h1: 50, h2: 42, h3: 34, h4: 26, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: true,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['velvet', 'purple', 'elegant', 'gradient'],
			version: '1.0.0',
		},
	},
	{
		id: 'tranquil',
		name: 'Tranquil',
		category: 'creative',
		primaryColor: '#0891b2',
		secondaryColor: '#06b6d4',
		backgroundColor: '#f0f9ff',
		textColor: '#0c4a6e',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'gradient',
			gradient: {
				type: 'linear',
				angle: 180,
				stops: [
					{ color: '#f0f9ff', position: 0 },
					{ color: '#e0f2fe', position: 30 },
					{ color: '#bae6fd', position: 70 },
					{ color: '#0891b2', position: 100 },
				],
			},
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#0c4a6e',
			bodyColor: '#0369a1',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['calm', 'blue', 'water', 'peaceful'],
			version: '1.0.0',
		},
	},
	{
		id: 'borealis',
		name: 'Borealis',
		category: 'professional',
		primaryColor: '#06b6d4',
		secondaryColor: '#0891b2',
		backgroundColor: '#374151',
		textColor: '#f9fafb',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#374151',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f9fafb',
			bodyColor: '#d1d5db',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['dark', 'professional', 'rounded', 'modern'],
			version: '1.0.0',
		},
	},
	{
		id: 'terracotta',
		name: 'Terracotta',
		category: 'basic',
		primaryColor: '#be185d',
		secondaryColor: '#ec4899',
		backgroundColor: '#fef2f2',
		textColor: '#7f1d1d',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#fef2f2',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#7f1d1d',
			bodyColor: '#be185d',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['earth', 'pink', 'warm', 'clay'],
			version: '1.0.0',
		},
	},
	{
		id: 'bubble-gum',
		name: 'Bubble Gum',
		category: 'creative',
		primaryColor: '#ec4899',
		secondaryColor: '#f472b6',
		backgroundColor: '#111827',
		textColor: '#f9fafb',
		headerFont: 'Poppins, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#111827',
		},
		illustrations: [],
		typography: {
			headingFont: 'Poppins, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#ec4899',
			bodyColor: '#f9fafb',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['pink', 'fun', 'playful', 'bubble'],
			version: '1.0.0',
		},
	},
	{
		id: 'snowball',
		name: 'Snowball',
		category: 'basic',
		primaryColor: '#1e40af',
		secondaryColor: '#2563eb',
		backgroundColor: '#f8fafc',
		textColor: '#1e293b',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#f8fafc',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1e293b',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['white', 'clean', 'minimal', 'snow'],
			version: '1.0.0',
		},
	},
	{
		id: 'pistachio',
		name: 'Pistachio',
		category: 'creative',
		primaryColor: '#059669',
		secondaryColor: '#10b981',
		backgroundColor: '#ecfdf5',
		textColor: '#064e3b',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#ecfdf5',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#064e3b',
			bodyColor: '#065f46',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['green', 'fresh', 'natural', 'pistachio'],
			version: '1.0.0',
		},
	},
	{
		id: 'piano',
		name: 'Piano',
		category: 'professional',
		primaryColor: '#f9fafb',
		secondaryColor: '#e5e7eb',
		backgroundColor: '#111827',
		textColor: '#1f2937',
		headerFont: 'Playfair Display, serif',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#111827',
		},
		illustrations: [],
		typography: {
			headingFont: 'Playfair Display, serif',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1f2937',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['black', 'white', 'contrast', 'elegant'],
			version: '1.0.0',
		},
	},
	{
		id: 'atacama',
		name: 'Atacama',
		category: 'creative',
		primaryColor: '#ec4899',
		secondaryColor: '#f472b6',
		backgroundColor: '#1f2937',
		textColor: '#f9fafb',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#1f2937',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f9fafb',
			bodyColor: '#ec4899',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['desert', 'pink', 'dark', 'modern'],
			version: '1.0.0',
		},
	},
	{
		id: 'wireframe',
		name: 'Wireframe',
		category: 'basic',
		primaryColor: '#374151',
		secondaryColor: '#6b7280',
		backgroundColor: '#f3f4f6',
		textColor: '#1f2937',
		headerFont: 'JetBrains Mono, monospace',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#f3f4f6',
		},
		illustrations: [],
		typography: {
			headingFont: 'JetBrains Mono, monospace',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1f2937',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0.5,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['minimal', 'monospace', 'dev', 'wireframe'],
			version: '1.0.0',
		},
	},
	{
		id: 'aurum',
		name: 'Aurum',
		category: 'professional',
		primaryColor: '#f59e0b',
		secondaryColor: '#d97706',
		backgroundColor: '#1f2937',
		textColor: '#f9fafb',
		headerFont: 'Crimson Text, serif',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#1f2937',
		},
		illustrations: [],
		typography: {
			headingFont: 'Crimson Text, serif',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f59e0b',
			bodyColor: '#f9fafb',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['gold', 'luxury', 'elegant', 'dark'],
			version: '1.0.0',
		},
	},
	{
		id: 'bee-happy',
		name: 'Bee Happy',
		category: 'creative',
		primaryColor: '#fbbf24',
		secondaryColor: '#f59e0b',
		backgroundColor: '#1f2937',
		textColor: '#f9fafb',
		headerFont: 'Poppins, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#1f2937',
		},
		illustrations: [],
		typography: {
			headingFont: 'Poppins, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#fbbf24',
			bodyColor: '#f9fafb',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['yellow', 'happy', 'bee', 'cheerful'],
			version: '1.0.0',
		},
	},
	{
		id: 'chocolate',
		name: 'Chocolate',
		category: 'professional',
		primaryColor: '#fbbf24',
		secondaryColor: '#f59e0b',
		backgroundColor: '#78350f',
		textColor: '#fef3c7',
		headerFont: 'Playfair Display, serif',
		bodyFont: 'Source Sans Pro, system-ui',
		background: {
			type: 'color',
			color: '#78350f',
		},
		illustrations: [],
		typography: {
			headingFont: 'Playfair Display, serif',
			bodyFont: 'Source Sans Pro, system-ui',
			headingColor: '#fef3c7',
			bodyColor: '#fed7aa',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['brown', 'chocolate', 'warm', 'rich'],
			version: '1.0.0',
		},
	},
	{
		id: 'cigar',
		name: 'Cigar',
		category: 'professional',
		primaryColor: '#6b7280',
		secondaryColor: '#9ca3af',
		backgroundColor: '#1f2937',
		textColor: '#f9fafb',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#1f2937',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f9fafb',
			bodyColor: '#d1d5db',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['dark', 'sophisticated', 'gray', 'minimal'],
			version: '1.0.0',
		},
	},
	{
		id: 'cornfield',
		name: 'Cornfield',
		category: 'creative',
		primaryColor: '#92400e',
		secondaryColor: '#b45309',
		backgroundColor: '#fbbf24',
		textColor: '#78350f',
		headerFont: 'Poppins, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#fbbf24',
		},
		illustrations: [],
		typography: {
			headingFont: 'Poppins, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#78350f',
			bodyColor: '#92400e',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['yellow', 'corn', 'warm', 'harvest'],
			version: '1.0.0',
		},
	},
	{
		id: 'basic-light',
		name: 'Basic Light',
		category: 'basic',
		primaryColor: '#374151',
		secondaryColor: '#6b7280',
		backgroundColor: '#ffffff',
		textColor: '#1f2937',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#ffffff',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1f2937',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['basic', 'simple', 'clean', 'white'],
			version: '1.0.0',
		},
	},
	{
		id: 'basic-dark',
		name: 'Basic Dark',
		category: 'basic',
		primaryColor: '#3b82f6',
		secondaryColor: '#60a5fa',
		backgroundColor: '#111827',
		textColor: '#f9fafb',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#111827',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f9fafb',
			bodyColor: '#d1d5db',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['basic', 'simple', 'dark', 'black'],
			version: '1.0.0',
		},
	},
	// Add remaining themes...
	{
		id: 'wine',
		name: 'Wine',
		category: 'professional',
		primaryColor: '#fbbf24',
		secondaryColor: '#f59e0b',
		backgroundColor: '#7c2d12',
		textColor: '#fef3c7',
		headerFont: 'Crimson Text, serif',
		bodyFont: 'Source Sans Pro, system-ui',
		background: {
			type: 'color',
			color: '#7c2d12',
		},
		illustrations: [],
		typography: {
			headingFont: 'Crimson Text, serif',
			bodyFont: 'Source Sans Pro, system-ui',
			headingColor: '#fef3c7',
			bodyColor: '#fed7aa',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['wine', 'burgundy', 'elegant', 'rich'],
			version: '1.0.0',
		},
	},
	{
		id: 'sprout',
		name: 'Sprout',
		category: 'creative',
		primaryColor: '#065f46',
		secondaryColor: '#059669',
		backgroundColor: '#10b981',
		textColor: '#064e3b',
		headerFont: 'Poppins, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'gradient',
			gradient: {
				type: 'radial',
				center: { x: 30, y: 30 },
				stops: [
					{ color: '#84cc16', position: 0 },
					{ color: '#65a30d', position: 40 },
					{ color: '#16a34a', position: 70 },
					{ color: '#15803d', position: 100 },
				],
			},
		},
		illustrations: [],
		typography: {
			headingFont: 'Poppins, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#064e3b',
			bodyColor: '#065f46',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['green', 'nature', 'growth', 'fresh', 'new'],
			version: '1.0.0',
		},
	},
	// === ADDITIONAL GALLERY THEMES ===
	{
		id: 'daktilo',
		name: 'Daktilo',
		category: 'basic',
		primaryColor: '#000000',
		secondaryColor: '#374151',
		backgroundColor: '#fef2f2',
		textColor: '#1f2937',
		headerFont: 'JetBrains Mono, monospace',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#fef2f2',
		},
		illustrations: [],
		typography: {
			headingFont: 'JetBrains Mono, monospace',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1f2937',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0.5,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['typewriter', 'minimal', 'border', 'retro'],
			version: '1.0.0',
		},
	},
	{
		id: 'dawn',
		name: 'Dawn',
		category: 'professional',
		primaryColor: '#3b82f6',
		secondaryColor: '#60a5fa',
		backgroundColor: '#111827',
		textColor: '#f9fafb',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#111827',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f9fafb',
			bodyColor: '#d1d5db',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['dark', 'clean', 'professional', 'minimal'],
			version: '1.0.0',
		},
	},
	{
		id: 'editoria',
		name: 'Editoria',
		category: 'professional',
		primaryColor: '#000000',
		secondaryColor: '#374151',
		backgroundColor: '#111827',
		textColor: '#1f2937',
		headerFont: 'JetBrains Mono, monospace',
		bodyFont: 'JetBrains Mono, monospace',
		background: {
			type: 'color',
			color: '#111827',
		},
		illustrations: [],
		typography: {
			headingFont: 'JetBrains Mono, monospace',
			bodyFont: 'JetBrains Mono, monospace',
			headingColor: '#1f2937',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0.5,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['monospace', 'editorial', 'code', 'technical'],
			version: '1.0.0',
		},
	},
	{
		id: 'flax',
		name: 'Flax',
		category: 'basic',
		primaryColor: '#374151',
		secondaryColor: '#6b7280',
		backgroundColor: '#f9fafb',
		textColor: '#1f2937',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#f9fafb',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1f2937',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['light', 'neutral', 'natural', 'clean'],
			version: '1.0.0',
		},
	},
	{
		id: 'gleam',
		name: 'Gleam',
		category: 'basic',
		primaryColor: '#374151',
		secondaryColor: '#6b7280',
		backgroundColor: '#ffffff',
		textColor: '#1f2937',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#ffffff',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1f2937',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['white', 'clean', 'minimal', 'bright'],
			version: '1.0.0',
		},
	},
	{
		id: 'gold-leaf',
		name: 'Gold Leaf',
		category: 'creative',
		primaryColor: '#d97706',
		secondaryColor: '#f59e0b',
		backgroundColor: '#fffbeb',
		textColor: '#78350f',
		headerFont: 'Playfair Display, serif',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#fffbeb',
		},
		illustrations: [],
		typography: {
			headingFont: 'Playfair Display, serif',
			bodyFont: 'Inter, system-ui',
			headingColor: '#78350f',
			bodyColor: '#d97706',
			headingSizes: { h1: 50, h2: 42, h3: 34, h4: 26, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['gold', 'luxury', 'elegant', 'ornate'],
			version: '1.0.0',
		},
	},
	{
		id: 'iris',
		name: 'Iris',
		category: 'basic',
		primaryColor: '#3730a3',
		secondaryColor: '#4338ca',
		backgroundColor: '#f8fafc',
		textColor: '#1e1b4b',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#f8fafc',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1e1b4b',
			bodyColor: '#3730a3',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['purple', 'iris', 'elegant', 'light'],
			version: '1.0.0',
		},
	},
	{
		id: 'keepsake',
		name: 'Keepsake',
		category: 'basic',
		primaryColor: '#1e40af',
		secondaryColor: '#2563eb',
		backgroundColor: '#dbeafe',
		textColor: '#1e293b',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#dbeafe',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#1e293b',
			bodyColor: '#374151',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['blue', 'memory', 'gentle', 'soft'],
			version: '1.0.0',
		},
	},
	{
		id: 'leimoon',
		name: 'Leimoon',
		category: 'creative',
		primaryColor: '#be185d',
		secondaryColor: '#ec4899',
		backgroundColor: '#fdf2f8',
		textColor: '#831843',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#fdf2f8',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#831843',
			bodyColor: '#be185d',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['pink', 'soft', 'feminine', 'gentle'],
			version: '1.0.0',
		},
	},
	{
		id: 'linen',
		name: 'Linen',
		category: 'basic',
		primaryColor: '#92400e',
		secondaryColor: '#d97706',
		backgroundColor: '#f5f5dc',
		textColor: '#78350f',
		headerFont: 'Crimson Text, serif',
		bodyFont: 'Source Sans Pro, system-ui',
		background: {
			type: 'color',
			color: '#f5f5dc',
		},
		illustrations: [],
		typography: {
			headingFont: 'Crimson Text, serif',
			bodyFont: 'Source Sans Pro, system-ui',
			headingColor: '#78350f',
			bodyColor: '#92400e',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['natural', 'fabric', 'warm', 'neutral'],
			version: '1.0.0',
		},
	},
	{
		id: 'malibu',
		name: 'Malibu',
		category: 'creative',
		primaryColor: '#be185d',
		secondaryColor: '#ec4899',
		backgroundColor: '#ff69b4',
		textColor: '#ffffff',
		headerFont: 'Poppins, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'gradient',
			gradient: {
				type: 'linear',
				angle: 45,
				stops: [
					{ color: '#ff1493', position: 0 },
					{ color: '#ff69b4', position: 50 },
					{ color: '#ffc0cb', position: 100 },
				],
			},
		},
		illustrations: [],
		typography: {
			headingFont: 'Poppins, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#ffffff',
			bodyColor: '#fce7f3',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: true,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['pink', 'vibrant', 'beach', 'summer'],
			version: '1.0.0',
		},
	},
	{
		id: 'moss-and-mist',
		name: 'Moss & Mist',
		category: 'professional',
		primaryColor: '#10b981',
		secondaryColor: '#059669',
		backgroundColor: '#1f2937',
		textColor: '#ecfdf5',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#1f2937',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#ecfdf5',
			bodyColor: '#10b981',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['green', 'nature', 'dark', 'forest'],
			version: '1.0.0',
		},
	},
	{
		id: 'plant-shop',
		name: 'Plant Shop',
		category: 'creative',
		primaryColor: '#059669',
		secondaryColor: '#10b981',
		backgroundColor: '#f0fdf4',
		textColor: '#064e3b',
		headerFont: 'Poppins, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#f0fdf4',
		},
		illustrations: [],
		typography: {
			headingFont: 'Poppins, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#064e3b',
			bodyColor: '#059669',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.5,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['green', 'plants', 'natural', 'organic'],
			version: '1.0.0',
		},
	},
	{
		id: 'rush',
		name: 'Rush',
		category: 'creative',
		primaryColor: '#be185d',
		secondaryColor: '#ec4899',
		backgroundColor: '#fca5a5',
		textColor: '#7f1d1d',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#fca5a5',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#7f1d1d',
			bodyColor: '#be185d',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['coral', 'warm', 'energetic', 'salmon'],
			version: '1.0.0',
		},
	},
	{
		id: 'shadow',
		name: 'Shadow',
		category: 'professional',
		primaryColor: '#6b7280',
		secondaryColor: '#9ca3af',
		backgroundColor: '#374151',
		textColor: '#f9fafb',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#374151',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f9fafb',
			bodyColor: '#d1d5db',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['gray', 'shadow', 'rounded', 'modern'],
			version: '1.0.0',
		},
	},
	{
		id: 'slate',
		name: 'Slate',
		category: 'professional',
		primaryColor: '#3b82f6',
		secondaryColor: '#60a5fa',
		backgroundColor: '#1e293b',
		textColor: '#f1f5f9',
		headerFont: 'Inter, system-ui',
		bodyFont: 'Inter, system-ui',
		background: {
			type: 'color',
			color: '#1e293b',
		},
		illustrations: [],
		typography: {
			headingFont: 'Inter, system-ui',
			bodyFont: 'Inter, system-ui',
			headingColor: '#f1f5f9',
			bodyColor: '#cbd5e1',
			headingSizes: { h1: 48, h2: 40, h3: 32, h4: 24, h5: 20, h6: 16 },
			lineHeight: 1.6,
			letterSpacing: 0,
		},
		accessibility: {
			contrastRatio: 4.5,
			highContrastMode: false,
			textShadowEnabled: false,
			backgroundImageDisabled: false,
			reducedMotion: false,
		},
		metadata: {
			createdBy: 'system',
			isCustom: false,
			tags: ['slate', 'professional', 'dark', 'modern'],
			version: '1.0.0',
		},
	},
]

// Utility functions for theme management
export function getThemesByCategory(category: SlideThemeType['category']): SlideThemeType[] {
	return ENHANCED_PRESET_THEMES.filter((theme) => theme.category === category)
}

export function getGradientThemes(): SlideThemeType[] {
	return ENHANCED_PRESET_THEMES.filter((theme) => theme.background.type === 'gradient')
}

export function getThemesWithIllustrations(): SlideThemeType[] {
	return ENHANCED_PRESET_THEMES.filter((theme) => theme.illustrations.length > 0)
}

export function generateRandomGradientTheme(): Partial<SlideThemeType> {
	const gradientTypes = ['linear', 'radial'] as const
	const colors = [
		'#ff6b6b',
		'#4ecdc4',
		'#45b7d1',
		'#96ceb4',
		'#ffeaa7',
		'#fab1a0',
		'#fd79a8',
		'#6c5ce7',
		'#a29bfe',
		'#74b9ff',
		'#0984e3',
		'#00b894',
		'#00cec9',
		'#55a3ff',
		'#fdcb6e',
		'#e17055',
		'#d63031',
		'#e84393',
	]

	const type = gradientTypes[Math.floor(Math.random() * gradientTypes.length)]
	const angle = Math.floor(Math.random() * 360)
	const stopCount = 3 + Math.floor(Math.random() * 3)

	const stops = Array.from({ length: stopCount }, (_, i) => ({
		color: colors[Math.floor(Math.random() * colors.length)],
		position: (100 / (stopCount - 1)) * i,
	}))

	return {
		background: {
			type: 'gradient',
			gradient: {
				type,
				angle: type === 'linear' ? angle : undefined,
				center: type === 'radial' ? { x: 50, y: 50 } : undefined,
				stops,
			},
		},
	}
}
